// <auto-generated />
using System;
using EmployeeManagment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagment.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeManagment.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/872.jpg",
                            Name = "Aurore Torphy",
                            Position = 5,
                            Salary = 31880m,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1180.jpg",
                            Name = "Julio Hessel",
                            Position = 0,
                            Salary = 30308m,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/177.jpg",
                            Name = "Elouise Kozey",
                            Position = 4,
                            Salary = 57729m,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/648.jpg",
                            Name = "Keaton Friesen",
                            Position = 2,
                            Salary = 46077m,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/382.jpg",
                            Name = "Tobin Jaskolski",
                            Position = 6,
                            Salary = 51363m,
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/670.jpg",
                            Name = "Royce Adams",
                            Position = 3,
                            Salary = 65532m,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/593.jpg",
                            Name = "Rebeca Emmerich",
                            Position = 5,
                            Salary = 89475m,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1032.jpg",
                            Name = "Vivienne Schaden",
                            Position = 4,
                            Salary = 33121m,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/415.jpg",
                            Name = "Lyla Kihn",
                            Position = 0,
                            Salary = 52858m,
                            Type = 3
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/324.jpg",
                            Name = "Oma Hoppe",
                            Position = 2,
                            Salary = 39607m,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/838.jpg",
                            Name = "Tristin Rodriguez",
                            Position = 2,
                            Salary = 78325m,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1090.jpg",
                            Name = "Halie Dach",
                            Position = 1,
                            Salary = 80745m,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/120.jpg",
                            Name = "Mary Douglas",
                            Position = 0,
                            Salary = 83906m,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/403.jpg",
                            Name = "Rodrigo Kuhn",
                            Position = 1,
                            Salary = 35633m,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/537.jpg",
                            Name = "Alejandrin Heidenreich",
                            Position = 1,
                            Salary = 59584m,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/499.jpg",
                            Name = "Ashlee Kozey",
                            Position = 2,
                            Salary = 55825m,
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/386.jpg",
                            Name = "Margarete Williamson",
                            Position = 4,
                            Salary = 51088m,
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/798.jpg",
                            Name = "Kayli Hermiston",
                            Position = 6,
                            Salary = 47355m,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/69.jpg",
                            Name = "Thaddeus Stracke",
                            Position = 9,
                            Salary = 34806m,
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1033.jpg",
                            Name = "Eve Hessel",
                            Position = 7,
                            Salary = 60023m,
                            Type = 3
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/861.jpg",
                            Name = "David Thiel",
                            Position = 0,
                            Salary = 65281m,
                            Type = 1
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/6.jpg",
                            Name = "Titus Heller",
                            Position = 0,
                            Salary = 63584m,
                            Type = 1
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/542.jpg",
                            Name = "Maybell Cummerata",
                            Position = 8,
                            Salary = 70435m,
                            Type = 1
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/971.jpg",
                            Name = "Kaden Kunze",
                            Position = 8,
                            Salary = 46856m,
                            Type = 3
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/616.jpg",
                            Name = "Keanu Heathcote",
                            Position = 9,
                            Salary = 53755m,
                            Type = 1
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/200.jpg",
                            Name = "Rebecca Leffler",
                            Position = 9,
                            Salary = 43493m,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/810.jpg",
                            Name = "Domenica Halvorson",
                            Position = 6,
                            Salary = 45472m,
                            Type = 3
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/837.jpg",
                            Name = "Destini Greenholt",
                            Position = 3,
                            Salary = 62180m,
                            Type = 1
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/189.jpg",
                            Name = "Maurice Kulas",
                            Position = 2,
                            Salary = 41268m,
                            Type = 3
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1199.jpg",
                            Name = "Aron Greenfelder",
                            Position = 9,
                            Salary = 91706m,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/364.jpg",
                            Name = "Deborah Abshire",
                            Position = 3,
                            Salary = 49770m,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/661.jpg",
                            Name = "Alexie Berge",
                            Position = 6,
                            Salary = 52690m,
                            Type = 2
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/600.jpg",
                            Name = "Aisha Corwin",
                            Position = 9,
                            Salary = 34076m,
                            Type = 2
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/711.jpg",
                            Name = "Laura Brown",
                            Position = 3,
                            Salary = 42871m,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/806.jpg",
                            Name = "Evelyn Kozey",
                            Position = 8,
                            Salary = 50402m,
                            Type = 2
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1140.jpg",
                            Name = "Bryon Bergnaum",
                            Position = 9,
                            Salary = 98824m,
                            Type = 3
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1122.jpg",
                            Name = "Efren Jones",
                            Position = 2,
                            Salary = 41688m,
                            Type = 3
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/74.jpg",
                            Name = "Madisyn Keebler",
                            Position = 9,
                            Salary = 66159m,
                            Type = 3
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1238.jpg",
                            Name = "Kamryn Quitzon",
                            Position = 8,
                            Salary = 44828m,
                            Type = 3
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/287.jpg",
                            Name = "Marques Quigley",
                            Position = 8,
                            Salary = 90205m,
                            Type = 3
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/682.jpg",
                            Name = "Sharon Hagenes",
                            Position = 6,
                            Salary = 81463m,
                            Type = 3
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/467.jpg",
                            Name = "Luna Leuschke",
                            Position = 8,
                            Salary = 59503m,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/43.jpg",
                            Name = "Albertha Bogisich",
                            Position = 1,
                            Salary = 97003m,
                            Type = 3
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/952.jpg",
                            Name = "Gunner Zieme",
                            Position = 1,
                            Salary = 36386m,
                            Type = 2
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/784.jpg",
                            Name = "Hettie Crooks",
                            Position = 8,
                            Salary = 50778m,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/559.jpg",
                            Name = "Delfina Ortiz",
                            Position = 3,
                            Salary = 85018m,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/946.jpg",
                            Name = "Deven Mayert",
                            Position = 3,
                            Salary = 84917m,
                            Type = 3
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/341.jpg",
                            Name = "Connie Friesen",
                            Position = 8,
                            Salary = 37336m,
                            Type = 1
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/793.jpg",
                            Name = "Marilyne Langosh",
                            Position = 2,
                            Salary = 68134m,
                            Type = 3
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/410.jpg",
                            Name = "Alisa Jaskolski",
                            Position = 0,
                            Salary = 91832m,
                            Type = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
